chat/urls.py
from django.conf.urls import url
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('chat/', views.chat,name='chat'),
    path('start-chat/', views.startChat,name='startChat'),
    url(r'^chat/(?P<room_name>[^/]+)/$', views.room, name='room'),
]

geryejwa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

def index(request):
	return render(request,'index.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('', include('chat.urls')),
    path('portal/', include('portal.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

index/models.py
from django.db.models.signals import post_save, pre_delete
from django.utils.translation import ugettext_lazy as _
from django.utils.deconstruct import deconstructible
from django.urls import reverse
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.auth.models import (
	AbstractBaseUser,PermissionsMixin
)
from django.dispatch import receiver
from django.conf import settings
from django.urls import reverse
from django.db import models

from django.conf import settings

from geryejwa.utils import (
	NOW,create_code,create_slug,
)

import random
import hashlib
import datetime
import string


# Create your models here.
from django.contrib.auth.models import BaseUserManager

class UserManager(BaseUserManager):
	def _create_user(self, email, password, **extra_fields):
		if not email:
			raise ValueError('The Email must be set')
		email = self.normalize_email(email)
		user = self.model(email=email,date_joined=NOW(), **extra_fields)
		user.set_password(password)
		user.save()
		return user

	def create_user(self,email,password,**extra_fields):
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)
		extra_fields.setdefault('is_active', True)

		if extra_fields.get('is_staff') is not True:
			raise ValueError('Superuser must have is_staff=True.')
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')
		return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(unique=True, null=True)
	first_name = models.CharField(_('First name'),max_length=255)
	last_name = models.CharField(_('Last name'),max_length=255)
	date_joined = models.DateTimeField(_('date joined'), default=NOW)

	is_staff = models.BooleanField(
		_('staff status'),
			default=False,
			help_text=_('Designates whether the user can log into this site.'),
		)
	is_active = models.BooleanField(
		_('active'),
			default=True,
			help_text=_(
				'Designates whether this user should be treated as active. '
				'Unselect this instead of deleting accounts.'
			),
		 )
	USERNAME_FIELD = 'email'
	objects = UserManager()

	def __str__(self):
		return self.email

	def get_full_name(self):
		return self.email

	def get_short_name(self):
		return self.email


class Profile(models.Model):
	date_created 					= models.DateTimeField(auto_now_add=True)
	date_modified					= models.DateTimeField(auto_now=True)

	slug 							= models.SlugField(max_length = 80)
	code 							= models.CharField(max_length=80,unique=True)

	user 							= models.OneToOneField(settings.AUTH_USER_MODEL,blank=True,null=True,
										on_delete=models.CASCADE)
	
	xphoto 							= models.ForeignKey("Photo",verbose_name="Photo",
										blank=True,null=True,on_delete=models.SET_NULL)

	MALE,FEMALE 					= 'M','F'
	GENDER 							= [(MALE,_('Male')),(FEMALE,_('Female'))]
	gender 							= models.CharField(max_length=2,blank=True,choices=GENDER)

	area_code 						= models.CharField(max_length=7,blank=True)
	phone 							= models.CharField(max_length=22,blank=True)
	
	done 							= models.BooleanField(default=False)
	date_done 						= models.DateTimeField(null=True,blank=True)

	activation_key 					= models.CharField(max_length=255,blank=True)
	date_key_expired 				= models.DateTimeField(blank=True,null=True)
	is_account_confirmed 			= models.BooleanField(default=False)
	date_account_confirmed 			= models.DateTimeField(blank=True,null=True)

	password_token 					= models.CharField(max_length=255,blank=True)
	date_password_token_expired 	= models.DateTimeField(blank=True,null=True)

	is_password_changed 			= models.BooleanField(default=True)
	date_password_changed 			= models.DateTimeField(blank=True,null=True)	

	nb_send_email					= models.IntegerField(default=0)
	email_sent 						= models.BooleanField(default=False)
	date_email_sent 				= models.DateTimeField(blank=True,null=True)

	def __str__(self):
		return self.full_name

	@property 
	def first_name(self):
		return self.user.first_name 

	@property 
	def full_name(self):
		if self.first_name or self.last_name:
			return "%s %s" % (self.first_name,self.last_name)
		return ""

	def get_absolute_url(self):
		return reverse('profile',args=[self.slug])

	@property
	def last_name(self):
		return self.user.last_name

	@property
	def photo_exists(self):
		if self.xphoto:
			return self.xphoto.photo_exists
		return False

	@property
	def email(self):
		return self.user.email

	
	def save(self, *args, **kwargs):
		if self.pk is None:
			self.code = create_code(self,40)	
			self.slug = create_slug(self,field_name='full_name')
		super(Profile, self).save(*args, **kwargs)

@receiver(post_save, sender=User)
def update_profile(sender, instance, created, **kwargs):
	if created:
		salt = hashlib.sha1(str(random.random()).encode()).hexdigest()
		activation_key = hashlib.sha1((salt).encode()).hexdigest()
		date_key_expired = NOW() + datetime.timedelta(hours=48)

		Profile.objects.create(user=instance,activation_key=activation_key,date_key_expired=date_key_expired)
	instance.profile.save()

@deconstructible
class object_directory_path(object):

	def __init__(self, prefix):
		self.prefix = prefix

	def __call__(self, instance, filename):
		ext = filename.split('.')[-1]
		date = NOW().strftime("%Y-%m-%dT%H:%M:%S")
		if instance.pk:
			ID = instance.pk
		else:
			ID = instance.generer(4).upper()

		filename = "uploaded-photos/%s/IMG-%s-ID-%s.%s" % (self.prefix,date,ID, ext)
		return filename

class Photo(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)

	code = models.CharField(max_length=11)

	photo = models.ImageField(upload_to=object_directory_path('original_size'), blank=True)
	photo600 = models.ImageField(upload_to=object_directory_path('600x600'), blank=True)
	photo450 = models.ImageField(upload_to=object_directory_path('450x450'), blank=True)
	photo300 = models.ImageField(upload_to=object_directory_path('300x300'), blank=True)
	photo200 = models.ImageField(upload_to=object_directory_path('200x200'), blank=True)
	photo150 = models.ImageField(upload_to=object_directory_path('150x150'), blank=True)
	photo100 = models.ImageField(upload_to=object_directory_path('100x100'), blank=True)
	photo75 = models.ImageField(upload_to=object_directory_path('75x75'), blank=True)
	photo37 = models.ImageField(upload_to=object_directory_path('37x37'), blank=True)
	photo18 = models.ImageField(upload_to=object_directory_path('18x18'), blank=True)

	def delete_all_photos(self):
		self.photo.delete()
		self.photo600.delete()
		self.photo450.delete()
		self.photo300.delete()
		self.photo200.delete()
		self.photo150.delete()
		self.photo100.delete()
		self.photo75.delete()
		self.photo37.delete()
		self.photo18.delete()

	def __str__(self):
		return str(self.id)

	@property
	def get_absolute_image_url(self):
		return self.photo.url

	@property
	def photo_exists(self):
		if self.photo and file_exists(self.photo):
			return True
		return False

	@property
	def width(self):
		return self.photo.width

	def generer(self,nb_letter):
		letters_digits = string.ascii_letters + string.digits
		aleatoire = [random.choice(letters_digits) for _ in range(nb_letter)]
		return ''.join(aleatoire)
		
	@property
	def height(self):
		return self.photo.height

	@property
	def ratio(self):
		if self.width and self.height:
			return self.width / self.height

	def save(self, *args, **kwargs):
		if self.pk is None:
			self.code = create_code(self,11)

		if self.photo:
			if not self.photo600 or not self.photo450 or not self.photo300 or not self.photo200 or self.photo150 \
			or not self.photo75	or not self.photo37 or not self.photo18:
			# SIZES = [(600,600),(450,450),(300,300),(200,200),(150,150),(100,100),(75,75),(37,37),(18,18)]
				p = CompressImage(self.photo)
				self.photo600 = p.resize(size=(600,600),render=True)
				self.photo450 = p.resize(size=(450,450),render=True)
				self.photo300 = p.resize(size=(300,300),render=True)
				self.photo200 = p.resize(size=(200,200),render=True)
				self.photo150 = p.resize(size=(150,150),render=True)
				self.photo100 = p.resize(size=(100,100),render=True)
				self.photo75 = p.resize(size=(75,75),render=True)
				self.photo37 = p.resize(size=(37,37),render=True)
				self.photo18 = p.resize(size=(18,18),render=True)
		super(Photo, self).save(*args, **kwargs)

@receiver(pre_delete, sender=Photo)
def deletePhotoWith(sender, instance, **kwargs):
	instance.delete_all_photos()

class Organization(models.Model):
	name = models.CharField(max_length=255)
	mission = models.TextField(max_length=4000)
	KIND = [
		('S',_('School')),('NS',_('Normal School')),
		('O',_('Orphanage')),('A',_('Association')),
		('NGO',_('Non-Governmental Organization')),
		('F',_('Foundation')),
		('-',_('Other')),
	]
	kind = models.CharField(max_length=3,choices=KIND)
	other_kind = models.CharField(max_length=3,choices=KIND)

	address = models.CharField(max_length=255)
	street_address = models.CharField(max_length=255)
	address_line_2 = models.CharField(max_length=255)
	city = models.CharField(max_length=255)
	state = models.CharField(max_length=255)
	zip_code = models.CharField(max_length=255,verbose_name=_('ZIP / Postal Code'))

	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	middle_name = models.CharField(max_length=255,blank=True)
	position = models.CharField(max_length=255)
	email = models.EmailField()
	phone = models.CharField(max_length=255)

	hear_about = models.TextField(verbose_name=_('How did you learn about Gèrye Jwa?'))
	support = models.TextField(verbose_name=_('How do you think Gerye Jwa can support your organization?'))

index/templates/index/about.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
	{% block media %}
	{% endblock %}
	<div class="mx-auto" id="index">
	<!-- <section class="d-flex align-items-center px-3" style="height: 300px;background-color:#006666">
		<div class="col-6">
			<h1 style="color: #85BC3B" class="text-center san-francisco upper">A title is here to help</h1>
		</div>

		<div class="col-6">
			<p class="white f-20">
				Quisque velit nisi pretium ut lacinia in eleme ntum id enim nulla quis lorem ut libero malesuada feugiat mauris blandit aliquet elit eget tincidunt nibh pulvinar aed porttitor lectus nibh ellent esque ipsum orci porta dapibus nulla porttitor accumsan tincidunt.
			</p>
		</div>
	</section> -->

	<section class="d-flex align-items-center text-center px-3 py-3" style="height: 500px;">
		<div class="col">
			<br>
			<h1 style="color: #006666" class="animatable bounceInLeft text-center san-francisco upper bold">Our Mission</h1>
			<div class="col-3">
					
			</div>
			<p class="white f-20 mx-5 px-5" style="color: #006666">Spread the power of optimism to help kids overcome adversity and live a good a life.
			<br>
			The Gèrye Jwa vision is to dramatically improve the quality of care to our nation’s most vulnerable citizens so that children grow up feeling safe, loved, and joyful.
			</p>
			<a href="#" class="btn btn-outline-success" style="width: 150px;border-radius: 20px">Join</a>
		</div>
	</section>
	<section class="d-flex text-center px-3 py-3" style="height: 770;background-color:#006666">
		<div class="col">
			<br><br>
			<h1 style="color: #85BC3B" class="animatable bounceIn text-center san-francisco upper bold">Our APPROACH</h1>
			<br><br>
			
			<div class="row" style="">
				<div class="col-2"></div>
				<div class="col-4">
					<img src="https://demos.artbees.net/jupiter/callirrhoe/wp-content/uploads/sites/46/2015/12/woman.png">
				</div>
					
				<div class="col-6">
					<p class="white f-20" style="color: ;margin-top: 5%">
						Sed porttitor lectus nibh curabitur arcu erat accumsan id imperdiet etimo porttitor at sem estibulum ante ipsum primis in faucibus orci luctus etimo ultrices posuere cubilia curae donec velit neque, auctor sit amet aliquam vel ullam corper sit amet ligula praesent sapien massa convallis  pellentesque nec egestas non nisi.auctor sit amet aliquam vel ullam corper sit amet ligula praesent sapien massa convallis  pellentesque nec egestas non nisi.
						<br>
						Sed porttitor lectus nibh curabitur arcu erat accumsan id imperdiet etimo porttitor at sem estibulum ante ipsum primis in faucibus orci luctus etimo ultrices posuere cubilia curae donec velit neque, auctor sit amet aliquam vel ullam corper sit amet ligula praesent sapien massa convallis  pellentesque nec egestas non nisi.auctor sit amet aliquam vel ullam corper sit amet ligula praesent sapien massa convallis  pellentesque nec egestas non nisi.
					</p>
				</div>			
			</div>
			<br>
			<!-- <a href="#" class="btn btn-outline-success" style="width: 150px">Join</a> -->
		</div>
	</section>
	<section class="d-flex text-center align-items-center px-3 py-3" style="height:500px;">
		<div class="col">
			<h1 style="color:#006666" class="text-center san-francisco upper bold mb-4">Our Story</h1>
			<div class="row " style="text-align: left;color: #006666">
				<div class="col-10 offset-1 f-20 text-center">
					<p class="">
						The Playmaker movement started in the United States in 1989, under the name Project Joy, to heal and strengthen children - especially those whose lives have been deeply affected by trauma.
					</p>
					<p>
						Over time, the movement became Life Is Good Playmakers after it was embraced by the <a href="#">Life Is Good Kids Foundation (LIGKF)</a>, a Boston-based non-profit organization.
					</p>
				</div>
				
			</div>
			<br>
			<a href="{% url 'story' %}" class="btn btn-outline-success" style="width: 150px">Read More...</a>
		</div>
	</section>


	
</div>

{% endblock %}

index/templates/index/become-gerye-jwa.html
{% extends 'base.html' %}
{% load static i18n %}

{% block body %}

{% block media %}
{% endblock %}

<div class="containe" style="min-height: 100vh" id="index">
	<form class="col-md-8 offset-2 mt-3 border p-4" style="background-color: #f0f8ff" action="" method="post">
		{% csrf_token %}
		<h4 class="upper bold">Gèrye Jwa Membership</h4><br>
		
		<div class="form-row form-group">
			<div class="col">
				<label>First Name <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.first_name.errors %}
					<i class="control-label">{{form.first_name.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.first_name}}
			</div>
			<div class="col">
				<label>Middle Name</label>
				<label class="label-error control-label">
				{% if form.middle_name.errors %}
					<i class="control-label">{{form.middle_name.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.middle_name}}
			</div>
			<div class="col">
				<label>Last Name <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.last_name.errors %}
					<i class="control-label">{{form.last_name.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.last_name}}
			</div>
		</div>		

		<div class="form-row form-group">
			<div class="col">
				<label>Address <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.address.errors %}
					<i class="control-label">{{form.address.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.address}}
			</div>
			<div class="col">
				<label>Street Address <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.street_address.errors %}
					<i class="control-label">{{form.street_address.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.street_address}}
			</div>

			<div class="col">
				<label>Address Line 2</label>
				<label class="label-error control-label">
				{% if form.address_line_2.errors %}
					<i class="control-label">{{form.address_line_2.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.address_line_2}}
			</div>
		</div>	
		<div class="form-row form-group">
			<div class="col">
				<label>City <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.city.errors %}
					<i class="control-label">{{form.city.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.city}}
			</div>
			<div class="col">
				<label>State / Province / Region <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.state.errors %}
					<i class="control-label">{{form.state.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.state}}
			</div>
			<div class="col">
				<label>ZIP / Postal Code <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.zip_code.errors %}
					<i class="control-label">{{form.zip_code.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.zip_code}}
			</div>
		</div>
		<div class="form-row form-group">
			<div class="col">
				<label>Country <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.country.errors %}
					<i class="control-label">{{form.country.errors.as_text}}</i>
				{%endif%}
				</label>
				<select class="form-control" name="country" id="id_country">
					{% include 'country.html' %}
				</select>
			</div>
			<div class="col">
				<label>Email <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.email.errors %}
					<i class="control-label">{{form.email.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.email}}
			</div>
			<div class="col">
				<label>Phone <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.phone.errors %}
					<i class="control-label">{{form.phone.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.phone}}
			</div>
		</div>
		
		<br>
		<div class="form-row form-group">
			<div class="col">
				<button type="submit" class="btn btn-success">Save</button>
			</div>
		</div>
	</form>
</div>

{% endblock %}

{% block script %}
	<script type="text/javascript">
		var kind = $('id_interests_-');
		if($(kind).prop("checked")){
			$("#cover-other").show();
			$("#cover-other input").focus();
		}else{
			$("#cover-other").hide();
		}

		$('#id_interests_-').on('click',function(){
			var kind = $(this);
			if($(kind).prop("checked")){
				$("#cover-other").show();
				$("#cover-other input").focus();
			}else{
				$("#cover-other").hide();
			}
		});
	</script>
{% endblock %}

index/templates/index/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block media %}{% endblock %}

{% block css %}{% endblock %}

{% block body %}
	<div class="mx-auto" id="index">
		<div class="h-100">
			<h1>Steps to become a gerye jwa</h1>
		</div>
	</div>
{% endblock %}

index/templates/index/partner-form.html
{% extends 'base.html' %}
{% load static i18n %}

{% block body %}

{% block media %}
{% endblock %}

<div class="containe" style="min-height: 100vh" id="index">
	<form class="col-md-8 offset-2 mt-3 border p-4" style="background-color: #f0f8ff" action="" method="post">
		{% csrf_token %}
		<h4 class="upper">Organization Form</h4>
		<p class="italic">Gèrye Jwa is open to new partnerships and is willing to come to you organization to help you create optimal environment, for the kids you serve and for your staff, if you invite us. Please take a few minutes to fill out this form and we will get back to you in a couple days.</p>
		<div class="form-row form-group">
			<div class="col">
				<label>Organization name <span class="red">*</span></label>
				{{form.name}}
			</div>
		</div>
		<div class="form-row form-group">
			<div class="col">
				<label>Mission of the organization <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.mission.errors %}
					<i class="control-label">{{form.mission.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.mission}}
			</div>
		</div>	
		<div class="form-row form-group">
			<div class="col-4">
				<label>Type of organization <span class="red">*</span></label><br>
				<label class="label-error control-label">
				{% if form.kind.errors %}
					<i class="control-label">{{form.kind.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.kind}}
			</div>
			<div class="col-4">
				<label>Other Type of organization <span class="red">*</span></label><br>
				<label class="label-error control-label">
				{% if form.other_kind.errors %}
					<i class="control-label">{{form.other_kind.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.other_kind}}
			</div>
		</div>		

		<div class="form-row form-group">
			<div class="col">
				<label>Address <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.address.errors %}
					<i class="control-label">{{form.address.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.address}}
			</div>
			<div class="col">
				<label>Street Address <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.street_address.errors %}
					<i class="control-label">{{form.street_address.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.street_address}}
			</div>

			<div class="col">
				<label>Address Line 2</label>
				<label class="label-error control-label">
				{% if form.address_line_2.errors %}
					<i class="control-label">{{form.address_line_2.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.address_line_2}}
			</div>
		</div>	
		<div class="form-row form-group">
			<div class="col">
				<label>City <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.city.errors %}
					<i class="control-label">{{form.city.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.city}}
			</div>
			<div class="col">
				<label>State / Province / Region <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.state.errors %}
					<i class="control-label">{{form.state.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.state}}
			</div>
			<div class="col">
				<label>ZIP / Postal Code <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.zip_code.errors %}
					<i class="control-label">{{form.zip_code.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.zip_code}}
			</div>
			<div class="w-100"></div>
			<div class="col-4 mt-2">
				<label>Country <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.country.errors %}
					<i class="control-label">{{form.country.errors.as_text}}</i>
				{%endif%}
				</label>
				<select class="form-control" name="country" id="id_country">
					{% include 'country.html' %}
				</select>
			</div>
		</div>
		<hr>
		<h5 class="bold">Personal Information</h5>
		<div class="form-row form-group">
			<div class="col">
				<label>First Name <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.first_name.errors %}
					<i class="control-label">{{form.first_name.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.first_name}}
			</div>
			<div class="col">
				<label>Middle Name</label>
				<label class="label-error control-label">
				{% if form.middle_name.errors %}
					<i class="control-label">{{form.middle_name.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.middle_name}}
			</div>
			<div class="col">
				<label>Last Name <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.last_name.errors %}
					<i class="control-label">{{form.last_name.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.last_name}}
			</div>
		</div>	
		<div class="form-row form-group">
			<div class="col-6">
				<label>Position <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.position.errors %}
					<i class="control-label">{{form.position.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.position}}
			</div>
		</div>
		<div class="form-row form-group">
			<div class="col">
				<label>Email <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.email.errors %}
					<i class="control-label">{{form.email.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.email}}
			</div>
			<div class="col">
				<label>Phone <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.phone.errors %}
					<i class="control-label">{{form.phone.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.phone}}
			</div>
		</div>	
		<div class="form-row form-group">
			<div class="col">
				<label>How did you learn about Gèrye Jwa? <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.hear_about.errors %}
					<i class="control-label">{{form.hear_about.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.hear_about}}
			</div>
		</div>
		<div class="form-row form-group">
			<div class="col">
				<label>How do you think Gerye Jwa can support your organization? <span class="red">*</span></label>
				<label class="label-error control-label">
				{% if form.support.errors %}
					<i class="control-label">{{form.support.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.support}}
			</div>
		</div>	
		<div class="form-row form-group">
			<div class="col">
				<label>Any other information we should know?</label>
				<label class="label-error control-label">
				{% if form.more_info.errors %}
					<i class="control-label">{{form.more_info.errors.as_text}}</i>
				{%endif%}
				</label>
				{{form.more_info}}
			</div>
		</div>	
		<div class="form-row form-group">
			<div class="col">
				<button type="submit" class="btn btn-success">Save</button>
			</div>
		</div>
	</form>
</div>

{% endblock %}

{% block script %}
	<script type="text/javascript">
		var kind = $('#id_kind').val();
		if(kind == '-'){
			$("#id_other_kind").closest("div").show();
		}else{
			$("#id_other_kind").closest("div").hide();
		}

		$('#id_kind').on('change',function(){
			var kind = $(this).val();
			if(kind == '-'){
				$("#id_other_kind").closest("div").show();
				$("#id_other_kind").focus();
			}else{
				$("#id_other_kind").closest("div").hide();
			}
		});
	</script>
{% endblock %}