chat/urls.py
from django.conf.urls import url
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('chat/', views.chat,name='chat'),
    path('start-chat/', views.startChat,name='startChat'),
    url(r'^chat/(?P<room_name>[^/]+)/$', views.room, name='room'),
]

geryejwa/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

def index(request):
	return render(request,'index.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('', include('chat.urls')),
    path('portal/', include('portal.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models
from django.contrib.sessions.models import Session
from index.models import Profile

# Create your models here.


class ChatCenter(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)

	guest_session_key = models.CharField(max_length=255) # The Anonymous user who starts the chat
	guest_email = models.EmailField()
	guest_name = models.CharField(max_length=255)

	token = models.CharField(max_length=70) # To join the chat
	joined = models.BooleanField(default=False) # Someone has joined the chat
	date_joined = models.DateTimeField(blank=True,null=True)

	# admins = models.ManyToManyField(Profile,blank=True,through='ChatAdmin') # Participants of chat center from Gerye Jwa

	ended = models.BooleanField(default=False)


class ChatAdmin(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)

	# user = models.ForeignKey(Profile,on_delete=models.CASCADE)
	chat_center = models.ForeignKey(ChatCenter,on_delete=models.CASCADE)

	is_active = models.DateTimeField(blank=True,null=True)
	added = models.BooleanField(default=False)
	date_added = models.DateTimeField(blank=True,null=True)
	added_by = models.PositiveIntegerField(blank=True,null=True) # ID of the admin in case he's benn added by someone else

class Chat(models.Model):
	date_created = models.DateTimeField(auto_now_add=True)
	date_modified = models.DateTimeField(auto_now=True)

	chat_center = models.ForeignKey(ChatCenter,on_delete=models.CASCADE)
	# user = models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,blank=True)
	content = models.TextField()

templates/chat-center.html
<div id="chat-center" class="chat">
	<div class="card">
		<div class="card-header msg_head">
			<div class="d-flex bd-highlight">
				<div class="img_cont">
					<img src="https://static.wixstatic.com/media/d059e2_4a6340b551207ce1f4b0a5f719b7b712.png/v1/fill/w_195,h_176,al_c,usm_0.66_1.00_0.01/d059e2_4a6340b551207ce1f4b0a5f719b7b712.png" class="rounded-circle user_img">
					<span class="offline"></span>
				</div>
				<div class="user_info">
					<span>Gerye Jwa Chat Center</span>
					<p>Someone will join you</p>
				</div>
			</div>
			<span id="action_menu_btn"><i class="fa fa-minus"></i></span>
			<div class="action_menu">
				<ul>
					<li><i class="fas fa-user-circle"></i> View profile</li>
					<li><i class="fas fa-users"></i> Add to close friends</li>
					<li><i class="fas fa-plus"></i> Add to group</li>
					<li><i class="fas fa-ban"></i> Block</li>
				</ul>
			</div>
		</div>

		<div class="card-body msg_card_body">
			{% if cc %}
			<p>Hello, {{cc.guest_name}}. How can we help you today?</p>
			{% if not cc.admins.all %}<p>No one is online at the moment, but we will quickly get there</p>{% endif %}
			
			{% for msg in cc.chat_set.all %}
				<div style="display: table;width: 100%" class="{% if not msg.user %}justify-content-start{% else %}justify-content-end{% endif %} mb-4">
					<div class="dimg_cont_msg left" style="display: table-cell; vertical-align: top;width: 15%">
						<img src="https://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" class="rounded-circle user_img_msg">
					</div>
					<div style="min-width: 100px;display: table-cell; vertical-align: top;" class="{% if not msg.user %}msg_cotainer{% else %}msg_cotainer_send{% endif %}">
						{{msg.content}}
						<span class="msg_time">8:40 AM, Today</span>
					</div>
				</div>
				<!-- <div class="d-flex justify-content-end mb-4">
					<div class="msg_cotainer_send">
						Hi Maryam I think it's 30 miles
						<span class="msg_time_send">8:55 AM, Today</span>
					</div>
					<div class="img_cont_msg">
						<img src="https://yt3.ggpht.com/a-/AJLlDp2tfEIfHjdh3f5ukUFjBFykKQaWGmacHNAL3g=s900-mo-c-c0xffffffff-rj-k-no" class="rounded-circle user_img_msg">
					</div> 
				</div>-->
			{% endfor %}
			{% else %}
			<div class="d-flex justify-content-start mb-4">
				<input type="text" placeholder="Enter your name" class="form-control form-control-sm type_msg" name="name">
			</div>
			<div class="d-flex justify-content-start mb-4">
				<input type="text" placeholder="Enter your email" class="form-control form-control-sm type_msg" name="email">
			</div>
			<button id="submit-chat-info" type="button" class="btn btn-success btn-sm"><i class="fa fa-circle-o-notch"></i> Start the chat</button>
			{% endif %}
		</div>
		{% if cc %}
		<div class="card-footer">
			<form action="" id="chat-content" method="post">{% csrf_token %}
			<div class="input-group">
				<div class="input-group-append">
					<span class="input-group-text attach_btn"><i class="fa fa-paperclip"></i></span>
				</div>
				<textarea name="content" class="form-control type_msg" style="resize: none" placeholder="Type your message..."></textarea>
				<div class="input-group-append">
					<span class="input-group-text send_btn"><i class="fa fa-location-arrow"></i></span>
				</div>
			</div>
			</form>
		</div>
		{% endif %}
	</div>
</div>

<style type="text/css">
	#chat-center{
		margin-top: auto;
		margin-bottom: auto;
		/*display: none;*/
		font-size: 12px;
		z-index: 101 !important;
	}
	#chat-center .card{
		height: 500px;
		border-radius: 15px !important;
		background: #7F7FD5;
       	background: -webkit-linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
        background: linear-gradient(to right, #91EAE4, #86A8E7, #7F7FD5);
        /*background-color: #fff;*/
        width: 350px;
	}
	#chat-center .contacts_body{
		padding:  0.75rem 0 !important;
		overflow-y: auto;
		white-space: nowrap;
	}
	#chat-center .msg_card_body{
		overflow-y: auto;
	}
	#chat-center .card-header{
		border-radius: 15px 15px 0 0 !important;
		border-bottom: 0 !important;
	}
 	#chat-center .card-footer{
		border-radius: 0 0 15px 15px !important;
		border-top: 0 !important;
	}
	#chat-center .search{
		border-radius: 15px 0 0 15px !important;
		background-color: rgba(0,0,0,0.3) !important;
		border:0 !important;
		color:white !important;
	}
	#chat-center .search:focus{
	  	box-shadow:none !important;
       	outline:0px !important;
	}
	#chat-center .type_msg{
		background-color: rgba(0,0,0,0.3) !important;
		border:0 !important;
		color:white !important;
		height: 60px !important;
		overflow-y: auto;
	}
	#chat-center .type_msg:focus{
		box-shadow:none !important;
      	outline:0px !important;
	}
	#chat-center .attach_btn{
		border-radius: 15px 0 0 15px !important;
		background-color: rgba(0,0,0,0.3) !important;
		border:0 !important;
		color: white !important;
		cursor: pointer;
	}
	#chat-center .send_btn{
		border-radius: 0 15px 15px 0 !important;
		background-color: rgba(0,0,0,0.3) !important;
		border:0 !important;
		color: white !important;
		cursor: pointer;
	}
	#chat-center .search_btn{
		border-radius: 0 15px 15px 0 !important;
		background-color: rgba(0,0,0,0.3) !important;
		border:0 !important;
		color: white !important;
		cursor: pointer;
	}
	#chat-center .contacts{
		list-style: none;
		padding: 0;
	}
	#chat-center .contacts li{
		width: 100% !important;
		padding: 5px 10px;
		margin-bottom: 15px !important;
	}
	#chat-center .active{
		background-color: rgba(0,0,0,0.3);
	}
	#chat-center .user_img{
		height: 70px;
		width: 70px;
	}
	#chat-center .user_img_msg{
		height: 40px;
		width: 40px;
		border:1.5px solid #f5f6fa;
	
	}
	#chat-center .img_cont{
		position: relative;
		height: 70px;
		width: 70px;
	}
	#chat-center .img_cont_msg{
		height: 40px;
		width: 40px;
	}
	#chat-center .online_icon{
		position: absolute;
		height: 15px;
		width:15px;
		background-color: #4cd137;
		border-radius: 50%;
		bottom: 0.2em;
		right: 0.4em;
		border:1.5px solid white;
	}
	#chat-center .offline{
		background-color: #c23616 !important;
		position: absolute;
		height: 15px;
		width:15px;
		border-radius: 50%;
		bottom: 0.2em;
		right: 0.4em;
		border:1.5px solid white;
	}
	#chat-center .user_info{
		margin-top: auto;
		margin-bottom: auto;
		margin-left: 15px;
	}
	#chat-center .user_info span{
		font-size: 20px;
		color: black;
	}
	#chat-center .user_info p{
		font-size: 10px;
		color: black;
	}
	#chat-center .video_cam{
		margin-left: 50px;
		margin-top: 5px;
	}
	#chat-center .video_cam span{
		color: white;
		font-size: 20px;
		cursor: pointer;
		margin-right: 20px;
	}
	#chat-center .msg_cotainer{
		margin-top: auto;
		margin-bottom: auto;
		margin-left: 10px;
		border-radius: 25px;
		background-color: #82ccdd;
		padding: 10px;
		position: relative;
	}
	#chat-center .msg_cotainer_send{
		margin-top: auto;
		margin-bottom: auto;
		margin-right: 10px;
		border-radius: 25px;
		background-color: #78e08f;
		padding: 10px;
		position: relative;
	}
	#chat-center .msg_time{
		position: absolute;
		left: 0;
		bottom: -15px;
		color: rgba(255,255,255,0.5);
		font-size: 10px;
	}
	#chat-center .msg_time_send{
		position: absolute;
		right:0;
		bottom: -15px;
		color: rgba(255,255,255,0.5);
		font-size: 10px;
	}
	#chat-center .msg_head{
		position: relative;
	}
	#action_menu_btn{
		position: absolute;
		right: 10px;
		top: 10px;
		/*color: white;*/
		cursor: pointer;
		font-size: 20px;
	}
	#chat-center .action_menu{
		z-index: 1;
		position: absolute;
		padding: 15px 0;
		background-color: rgba(0,0,0,0.5);
		color: white;
		border-radius: 15px;
		top: 30px;
		right: 15px;
		display: none;
	}
	#chat-center .action_menu ul{
		list-style: none;
		padding: 0;
		margin: 0;
	}
	#chat-center .action_menu ul li{
		width: 100%;
		padding: 10px 15px;
		margin-bottom: 5px;
	}
	#chat-center .action_menu ul li i{
		padding-right: 10px;
	
	}
	#chat-center .action_menu ul li:hover{
		cursor: pointer;
		background-color: rgba(0,0,0,0.2);
	}
	@media(max-width: 576px){
		#chat-center .contacts_card{
			margin-bottom: 15px !important;
		}
	}
</style>

templates/country.html
<optgroup label="North America">
    <option value="US">United States</option>
    <option value="UM">United States Minor Outlying Islands</option>
    <option value="CA">Canada</option>
    <option value="MX">Mexico</option>
    <option value="TC">Turks and Caicos Islands</option>
</optgroup>
<optgroup label="Central America">
    <option value="PA">Panama</option>
    <option value="CR">Costa Rica</option>
    <option value="SV">El Salvador</option>
    <option value="GT">Guatemala</option>
    <option value="NI">Nicaragua</option>
    <option value="HN">Honduras</option>
    <option value="BZ">Belize</option>
</optgroup>
<optgroup label="South America">
    <option value="AR">Argentina</option>
    <option value="BO">Bolivia</option>
    <option value="BR">Brazil</option>
    <option value="CL">Chile</option>
    <option value="CO">Colombia</option>
    <option value="EC">Ecuador</option>
    <option value="FK">Falkland Islands (Malvinas)</option>
    <option value="GF">French Guiana</option>
    <option value="GY">Guyana</option>
    <option value="PY">Paraguay</option>
    <option value="PE">Peru</option>
    <option value="SR">Suriname</option>
    <option value="UY">Uruguay</option>
    <option value="VE">Venezuela</option>
</optgroup>
<optgroup label="Caribbean">
    <option value="AI">Anguilla</option>
    <option value="AG">Antigua and Barbuda</option>
    <option value="AW">Aruba</option>
    <option value="BS">Bahamas</option>
    <option value="BB">Barbados</option>
    <option value="BM">Bermuda</option>
    <option value="VG">British Virgin Islands</option>
    <option value="KY">Cayman Islands</option>
    <option value="CU">Cuba</option>
    <option value="DM">Dominica</option>
    <option value="DO">Dominican Republic</option>
    <option value="GD">Grenada</option>
    <option value="GP">Guadeloupe</option>
    <option selected value="HT">Haiti</option>
    <option value="JM">Jamaica</option>
    <option value="MQ">Martinique</option>
    <option value="MS">Montserrat</option>
    <option value="AN">Netherlands Antilles</option>
    <option value="PR">Puerto Rico</option>
    <option value="KN">Saint Kitts and Nevis</option>
     <option value="LC">Saint Lucia</option>
    <option value="VC">Saint Vincent and the Grenadines</option>
    <option value="TT">Trinidad and Tobago</option>
    <option value="VI">US Virgin Islands</option>
</optgroup>
<optgroup label="Europe">
    <option value="GB">United Kingdom</option>
    <option value="AL">Albania</option>
    <option value="AD">Andorra</option>
    <option value="AT">Austria</option>
    <option value="BY">Belarus</option>
    <option value="BE">Belgium</option>
    <option value="BA">Bosnia and Herzegovina</option>
    <option value="BG">Bulgaria</option>
    <option value="HR">Croatia (Hrvatska)</option>
    <option value="CY">Cyprus</option>
    <option value="CZ">Czech Republic</option>
    <option value="FR">France</option>
    <option value="GI">Gibraltar</option>
    <option value="DE">Germany</option>
    <option value="GR">Greece</option>
    <option value="VA">Holy See (Vatican City State)</option>
    <option value="HU">Hungary</option>
    <option value="IT">Italy</option>
    <option value="LI">Liechtenstein</option>
    <option value="LU">Luxembourg</option>
    <option value="MK">Macedonia</option>
    <option value="MT">Malta</option>
    <option value="MD">Moldova</option>
    <option value="MC">Monaco</option>
    <option value="ME">Montenegro</option>
    <option value="NL">Netherlands</option>
    <option value="PL">Poland</option>
    <option value="PT">Portugal</option>
    <option value="RO">Romania</option>
    <option value="SM">San Marino</option>
    <option value="RS">Serbia</option>
    <option value="SK">Slovakia</option>
    <option value="SI">Slovenia</option>
    <option value="ES">Spain</option>
    <option value="UA">Ukraine</option>
    <option value="DK">Denmark</option>
    <option value="EE">Estonia</option>
    <option value="FO">Faroe Islands</option>
    <option value="FI">Finland</option>
    <option value="GL">Greenland</option>
    <option value="IS">Iceland</option>
    <option value="IE">Ireland</option>
    <option value="LV">Latvia</option>
    <option value="LT">Lithuania</option>
    <option value="NO">Norway</option>
    <option value="SJ">Svalbard and Jan Mayen Islands</option>
    <option value="SE">Sweden</option>
    <option value="CH">Switzerland</option>
    <option value="TR">Turkey</option>
</optgroup>
<optgroup label="Africa">
    <option value="DZ">Algeria</option>
    <option value="AO">Angola</option>
    <option value="BJ">Benin</option>
    <option value="BW">Botswana</option>
    <option value="BF">Burkina Faso</option>
    <option value="BI">Burundi</option>
    <option value="CM">Cameroon</option>
    <option value="CV">Cape Verde</option>
    <option value="CF">Central African Republic</option>
    <option value="TD">Chad</option>
    <option value="KM">Comoros</option>
    <option value="CG">Congo</option>
    <option value="CD">Congo, the Democratic Republic of the</option>
    <option value="DJ">Dijibouti</option>
    <option value="EG">Egypt</option>
    <option value="GQ">Equatorial Guinea</option>
    <option value="ER">Eritrea</option>
    <option value="ET">Ethiopia</option>
    <option value="GA">Gabon</option>
    <option value="GM">Gambia</option>
    <option value="GH">Ghana</option>
    <option value="GN">Guinea</option>
    <option value="GW">Guinea-Bissau</option>
    <option value="CI">Cote d'Ivoire (Ivory Coast)</option>
    <option value="KE">Kenya</option>
    <option value="LS">Lesotho</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libya</option>
    <option value="MG">Madagascar</option>
    <option value="MW">Malawi</option>
    <option value="ML">Mali</option>
    <option value="MR">Mauritania</option>
    <option value="MU">Mauritius</option>
    <option value="YT">Mayotte</option>
    <option value="MA">Morocco</option>
    <option value="MZ">Mozambique</option>
    <option value="NA">Namibia</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="RE">Reunion</option>
    <option value="RW">Rwanda</option>
    <option value="ST">Sao Tome and Principe</option>
    <option value="SH">Saint Helena</option>
    <option value="SN">Senegal</option>
    <option value="SC">Seychelles</option>
    <option value="SL">Sierra Leone</option>
    <option value="SO">Somalia</option>
    <option value="ZA">South Africa</option>
    <option value="SS">South Sudan</option>
    <option value="SD">Sudan</option>
    <option value="SZ">Swaziland</option>
    <option value="TZ">Tanzania</option>
    <option value="TG">Togo</option>
    <option value="TN">Tunisia</option>
    <option value="UG">Uganda</option>
    <option value="EH">Western Sahara</option>
    <option value="ZM">Zambia</option>
    <option value="ZW">Zimbabwe</option>
</optgroup>
<option value="AQ">Antarctica</option>

templates/footer.html
<style type="text/css">
	footer li a:hover{
		color: turquoise;
		text-decoration: none;
	}
	footer li a{
		color: #fff;
	}
	footer h5{
		text-transform: uppercase;
		font-family: san-francisco;
		font-weight: bold
	}
</style>
<footer class="py-5" style="background-color: #798686	">
	<div class="d-flex px-3">
		<div class="col-3 text-center">
			<img src="https://static.wixstatic.com/media/d059e2_4a6340b551207ce1f4b0a5f719b7b712.png/v1/fill/w_195,h_176,al_c,usm_0.66_1.00_0.01/d059e2_4a6340b551207ce1f4b0a5f719b7b712.png" height="80">
		</div>
		<div class="col-3">
			<h5>Features</h5>
			<ul class="list-unstyled text-small">
				<li><a class="" href="#">Cool stuff</a></li>
				<li><a class="" href="#">Random feature</a></li>
				<li><a class="" href="#">Team feature</a></li>
				<li><a class="" href="#">Stuff for developers</a></li>
				<li><a class="" href="#">Another one</a></li>
				<li><a class="" href="{% url 'portal' %}">Portal</a></li>
			</ul>
		</div>
		<div class="col-3">
			<h5>Resources</h5>
			<ul class="list-unstyled text-small">
				<li><a class="" href="#">Business</a></li>
				<li><a class="" href="#">Education</a></li>
				<li><a class="" href="#">Government</a></li>
				<li><a class="" href="#">Gaming</a></li>
			</ul>
		</div>
		<div class="col-3">
			<h5>About</h5>
			<ul class="list-unstyled text-small">
				<li><a class="" href="{% url 'team' %}">Team</a></li>
				<li><a class="" href="{% url 'community' %}">Community</a></li>
				<li><a class="" href="{% url 'story' %}">Story</a></li>
				<li><a class="" href="{% url 'partners' %}">Partners</a></li>
			</ul>
			<a href="#" class="text-white"><i class="fa fa-facebook"></i></a>
			<a href="#" class="text-white"><i class="fa fa-twitter"></i></a>
			<a href="#" class="text-white"><i class="fa fa-linkedin"></i></a>
			<a href="#" class="text-white"><i class="fa fa-soundcloud"></i></a>
			<a href="#" class="text-white"><i class="fa fa-instagram"></i></a>
		</div>
	</div>
</footer>

templates/navbar-top.html
{% load i18n %}
<div id="navbar-top" class="d-flex px-5 align-items-center" style="height: 120px;background-color: #f0f8ff;border-bottom: solid 3px white;">
	<div class="col-8">
		<div style="display: inline-block"><img style="margin-top: -25px" src="https://static.wixstatic.com/media/d059e2_4a6340b551207ce1f4b0a5f719b7b712.png/v1/fill/w_195,h_176,al_c,usm_0.66_1.00_0.01/d059e2_4a6340b551207ce1f4b0a5f719b7b712.png" height="120"></div>
	
		<div style="display: inline-block"><h1 class="gamja display-3" style="color:#458b74;margin-top: 25px">GERYE JWA</h1></div>
	</div>
	<div class="col float-right pull-right">
		<div class="float-right right">
			<!-- <a class="mx-1" href="#">English</a> -->
			<span class="gray bold"><i class="fa fa-circle"></i> English</span>
			<a title="{% trans 'Translate into french' %}" data-toggle='tooltip' class="mx-1" href="{% url 'set_language' %}?lg=fr&next={{request.path}}">Francais</a>
		</div>
	</div>
</div>

templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-lg px-5" style="z-index: 100000;width: 100%;background-color:#006666;box-shadow: none;border-bottom: solid 1px gray;">
	
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav rubik mr-auto">
			<li class="nav-item {% if active_item == 'index' %}active{% endif %}">
				<a class="nav-link" href="/"><i class="fa fa-home"></i> Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item dropdown bendme">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				 {% trans 'About' %}
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{% url 'about' %}">{% trans 'us' %}</a>
					<a class="dropdown-item" href="{% url 'team' %}">{% trans 'Our team' %}</a>
					<a class="dropdown-item" href="{% url 'partners' %}">{% trans 'Our partners' %}</a>
				</div>
			</li>

			<li class="nav-item dropdown bendme">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> {% trans 'Our program' %}
				</a>
				<div class="dropdown-menu" aria-labelledby="navbarDropdown">
					<a class="dropdown-item {% if request.path == '/program/' %}anchor{% endif %}" href="{% url 'program' %}#what-we-do">{% trans 'What we do' %}</a>
					<a class="dropdown-item {% if request.path == '/program/' %}anchor{% endif %}" href="{% url 'program' %}#why-we-do-it">{% trans 'Why we do it' %}</a>
					<a class="dropdown-item {% if request.path == '/program/' %}anchor{% endif %}" href="{% url 'program' %}#our-trainings">{% trans 'Our trainings' %}</a>
					<a class="dropdown-item {% if request.path == '/program/' %}anchor{% endif %}" href="{% url 'community' %}">{% trans 'Our community' %}</a>
				</div>
			</li>
			<li class="nav-item {% if active_item == 'involve' %}active{% endif %}">
				<a class="nav-link" href="{% url 'involve' %}"> Get involved</a>
			</li>
			<li class="nav-item {% if active_item == 'donate' %}active{% endif %}">
				<a class="nav-link" href="{% url 'donate' %}"> Donate</a>
			</li>
			<li class="nav-item {% if active_item == 'contact' %}active{% endif %}">
				<a class="nav-link" href="{% url 'contact' %}"><i class="fa fa-phone"></i> Contact us</a>
			</li>
		</ul>

		<!-- <form class="form-inline my-2 my-lg-0">
			<input class="form-control form-control-sm mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success btn-sm my-2 my-sm-0" type="submit">Search</button>
		</form> -->
		<ul class="navbar-nav">
			<li class="nav-item navbar-right">
				<button title="" id="toggle-audio" class="btn btn-xs btn-success"><i class="fa fa-play"></i></button>
			</li>
		</ul>
	</div>
</nav>